name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == '@dungpham91'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved for owner pull request"
