name: Docker Build

on:
  push:
    branches: [main]

### Ensures that only one CI task per branch/environment will run at a time ###
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Log in to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push docker image
        shell: bash
        env:
          REGISTRY: dungpham91
          REPOSITORY: rds-outpost-exporter
        run: |
          TAG_VERSION=$(cat VERSION)

          docker build \
            -t $REGISTRY/$REPOSITORY:${TAG_VERSION} \
            -t $REGISTRY/$REPOSITORY:latest \
            -f Dockerfile .

          echo "Pushing image to repository..."
          docker push $REGISTRY/$REPOSITORY --all-tags
