name: Kubesec Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 0 * * *'

### Ensures that only one CI task per branch/environment will run at a time ###
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  kubesec:
    name: Kubesec
    runs-on: ubuntu-20.04
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Check helm chart exists
        id: check_chart_exists
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: "chart/Chart.yaml"

      - name: File exists
        if: steps.check_chart_exists.outputs.files_exists == 'true'
        run: echo "Helm chart exists !"

      - name: Collect all yaml
        if: steps.check_chart_exists.outputs.files_exists == 'true'
        run: find ./chart -type f -name "*.yaml" -exec sh -c "echo '---' | cat - {}" \; > all.yaml

      - name: Run kubesec scanner
        if: steps.check_chart_exists.outputs.files_exists == 'true'
        uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14 # v0.0.2
        with:
          input: all.yaml
          format: template
          template: template/sarif.tpl
          output: kubesec-results.sarif
          exit-code: "0"

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@6db8d6351fd0be61f9ed8ebd12ccd35dcec51fea # v3.26.11
        if: always() && steps.check_chart_exists.outputs.files_exists == 'true'
        with:
          sarif_file: kubesec-results.sarif
          wait-for-processing: true
