name: Kubesec Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 0 * * *'

### Ensures that only one CI task per branch/environment will run at a time ###
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kubesec:
    name: Kubesec
    runs-on: ubuntu-20.04
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Collect all yaml
        run: find ./chart -type f -name "*.yaml" -exec sh -c "echo '---' | cat - {}" \; > all.yaml

      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@main
        with:
          input: all.yaml
          format: template
          template: template/sarif.tpl
          output: kubesec-results.sarif
          exit-code: "0"

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: kubesec-results.sarif
          wait-for-processing: true
